services:
  - type: web
    name: key-shop-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
    envVars:
      - key: RENDER
        value: true
